name: "\U0001F41B Bug report"
description: Create a report to help us improve.
labels:
  - "bug"
  - "help wanted"
body:
  - type: textarea
    attributes:
      label: 📄 Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ⛏ To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: ⚒ Expected behaviour
      description:
        A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: 🖥 Client version
      description: |
        - Device: Desktop (or Mobile and so on)
        - OS: [e.g. Windows 11 Build xxx]
        - Version: [e.g. KitX Dashboard v3.22.04]
  - type: textarea
    attributes:
      label: 🖼 Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: 📎 Additional context
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: |
        ---
        ### FAQ (Snippet)

        Below are some questions that are found in the FAQ.

        #### Q: My KitX Dashboard shows no devices.

        **Ans:** Check your personal network environment first before create an issue.
