name: kitx_mobile
description: Mobile Client for KitX

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter

#  intl: ^0.17.0
  wifi_iot: ^0.3.17
  flutter_i18n: ^0.32.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_i18n: ^0.32.4
#  device_info: ^2.0.3
  wifi_iot: ^0.3.17

flutter:
  uses-material-design: true

  assets:
    - assets/KitX-Background.png
#    - assets/
    - assets/i18n/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  generate: true #
