name: kitx_mobile
description: Mobile Client for KitX

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.24.10+6829

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  badges: ^3.1.2 # 徽章
  battery_plus: ^5.0.3 # 电池数据
  community_material_icon: ^5.9.55 # Material Design Icons 社区贡献
  concentric_transition: ^1.0.3 # 同心过渡动画
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  device_info_plus: ^9.1.1 # 设备信息
  f_logs: ^2.0.1 # 日志管理
  flutter: # Flutter
    sdk: flutter
  flutter_blue_plus: ^1.31.15 # 蓝牙
  # flutter_i18n: ^0.32.4 # 国际化
  # flutter_logs: ^2.1.7 # 日志
  flutter_chat_ui: ^1.6.12 # Chat UI
  get: ^4.6.6 # 状态管理
  # intl: ^0.17.0
  # mac_address: ^1.0.0 # 获取 MAC  p.s. iOS 未实现
  kitx_shared_dart: ^3.24.10+6829-patch-1
  network_info_plus: ^4.1.0 # 网络信息
  package_info_plus: ^5.0.1 # 包信息
  permission_handler: ^11.3.0 # 权限管理
  sensors_plus: ^4.0.2 # 传感器
  shared_preferences: ^2.2.2
  sliding_up_panel: ^2.0.0+1 # 向上滑动布局
  # sms_receiver: ^0.4.1 # 短信接收
  stack_trace: ^1.11.1
  url_launcher: ^6.2.4 # 打开链接
  vibration: ^1.8.4 # 手机震动
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_gen: ^5.4.0 # 生成工具
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  generate: true #
