name: Build APK

on:
  push:
    branches:
      - main
    paths-ignore:
      # - '.*/**'
      - 'kitx_mobile/.*/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'
          channel: 'stable'
      - run: flutter --version
      - working-directory: kitx_mobile
        run: |
          java --version
          flutter pub get
          flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: kitx_mobile/build/app/outputs/flutter-apk/
