name: Build APK

on:
  push:
    tags:
      - "v*"
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "kitx_mobile/.*/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".*/**"
      - "**/*.md"
      - "kitx_mobile/.*/**"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

    #   - uses: subosito/flutter-action@v2
    #     with:
    #       channel: "stable"
    #       cache: true

      - name: "Setting environment"
        run: |
          export PATH="$PWD/.flutter:$PATH"

      - name: "[Debug] Flutter Version"
        run: |
          flutter --version

      - name: "[Debug] Flutter Doctor"
        run: |
          flutter doctor -v

      - name: "[Debug] Java Version"
        run: |
          java --version

      - name: "Setting Signing Info"
        working-directory: .github/scripts
        shell: pwsh
        env:
          KeyPassword: ${{ secrets.JKS_KEYPWD }}
          StorePassword: ${{ secrets.JKS_STOREPWD }}
          KeyAlias: ${{ secrets.JKS_KEYALIAS }}
          StoreFile: ${{ secrets.JKS_STOREFILE }}
          JksBase64: ${{ secrets.JKS_BASE64 }}
        run: |
          ./set-sign-info.ps1 -keyPassword $env:KeyPassword -storePassword $env:StorePassword -keyAlias $env:KeyAlias -storeFile $env:StoreFile -jksBase64 $env:JksBase64

      - name: Build
        working-directory: kitx_mobile
        run: |
          python build.py

          # DATA=$(cat data.json)

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Auto release by Actions.
          draft: false
          prerelease: false
          files: |
            kitx_mobile/.ci_cd/*.apk
            kitx_mobile/.ci_cd/*.sha1
