name: "Pull Request Labeler"
on:
    pull_request:
        types:
            - closed

jobs:
    pr-merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ["merged"]
                      })
